os: linux
dist: xenial
sudo: required
language: python
python:
  - "3.7"
services:
  - docker
install:
  - pip install pre-commit
stages:
  - lint
jobs:
  include:
    - stage: lint
      script:
        - pre-commit run --all-files
    - stage: test:unit
      script:
        - docker-compose -f "docker-compose.test.yml" run -e COVERALLS_REPO_TOKEN="$COVERALLS_REPO_TOKEN" -e TRAVIS_JOB_ID="$TRAVIS_JOB_ID" -e TRAVIS_BRANCH="$TRAVIS_BRANCH" docupload sh -c "pipenv run python -m coverage run --source='.' manage.py test && pipenv run coveralls"
