# Generated by Django 2.0 on 2018-12-02 10:19
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confidentiality',
            name='total_docs',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='filetype',
            name='total_docs',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='language',
            name='total_docs',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
